### ISSUE TITLE
How to import bootstrap css in the main.css?

### ISSUE THREAD

**Issue by johhansantana** [Hashnode/mern-starter#274]
Hello

I'm trying to add bootstrap css to my app created via mern cli.

I see the `main.css` file and I do

`@import "../node_modules/bootstrap/dist/css/bootstrap-flex.css";`

When I refresh the app I see that it imported a few things
<img width="324" alt="screen shot 2016-12-12 at 8 45 04 pm" src="https://cloud.githubusercontent.com/assets/9933887/21122953/ea90e612-c0ab-11e6-901b-456f85ad53ed.png">

 but I don't see any styling, if I try to do custom classes there like

```css
.btn-primary {
  color: #fff;
  background-color: #0275d8;
  border-color: #0275d8;
}
```

the button doesn't change styling either.

Am I missing something?
